name: CI/CD Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: ./gradlew build

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk


      - name: Deploy to Firebase App Distribution
        run: |
          npm install -g firebase-tools
          TAG=$(echo ${GITHUB_REF/refs\/tags\//})
          firebase appdistribution:distribute --app ${{ secrets.FIREBASE_APP_ID }} --token ${{ secrets.FIREBASE_TOKEN }} --release-notes "MeLi Mobile Candidate ($TAG)" --release-binary-file app/build/outputs/apk/release/app-release.apk
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}