name: CI/CD Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: build gradle
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: ./gradlew build

      - name: codeclimate analysis
        uses: remarkablemark/setup-codeclimate@v2

      - name: Run Test and Upload Coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
            ./gradlew build
            cc-test-reporter format-coverage /home/runner/work/MeLi-Mobile-Candidate/MeLi-Mobile-Candidate/build/classes/java/main/jacocoTestReport.xml:jacoco --input-type jacoco
            cc-test-reporter before-build
            cc-test-reporter after-build --exit-code $?

      - name: build release
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: ./gradlew build
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app/build/outputs/apk/release/app-release-unsigned.apk