name: CI/CD Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: ./gradlew build

      - name: Setup Codeclimate
        uses: remarkablemark/setup-codeclimate@v2

      - name: Codeclimate Analysis
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: |
            cc-test-reporter before-build

      - name: Build release
        run: ./gradlew assembleRelease

      - name: Upload artifact to firebase app distribution
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: app/build/outputs/apk/release/app-release-unsigned.apk