name: CI/CD Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Add Firebase Key
        env:
          FIREBASE_KEY: $
        run:
          echo FIREBASE_KEY=\"$FIREBASE_KEY\ > ./local.properties

      - name: Verify local.properties
        run: |
          if [ -f ./local.properties ]; then
            echo "====================================="
            echo "local.properties created with success"
            echo "====================================="
            ls ./local.properties | awk '{print "<a href=\"" $0 "\">"$0"</a>"}'
          else
            echo "====================================="
            echo "ERROR: local.properties not found"
            echo "====================================="
          fi 

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run CodeClimate
        run: |
          # Replace the command with CodeClimate CLI command to run analysis
          # Example command: codeclimate analyze --dev
          echo "Running CodeClimate analysis"

      - name: Firebase deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}