name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Analyze with SonarCloud

        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=dosSantos-Paulo_MeLi-Mobile-Candidate
            -Dsonar.organization=dossantos-paulo