name: Scan with Detekt

on:
  pull_request:

jobs:
  without-type-resolution:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run detekt
        run: |
          ./gradlew detekt
          if [ $? -eq 0 ]; then
            echo "Detekt scan successful."
          else
            echo "Detekt scan failed. Please fix the issues and try again."
            exit 1
          fi