name: Remove google-services.json from Git cache

on:
  push:
    branches: [ main ]

jobs:
  remove_google_services_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove google-services.json from Git cache
        run: |
          git rm --cached app/google-services.json
          git commit -m "Remove google-services.json from Git cache" || echo "No changes to commit"
