name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches: [ "develop" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}