name: Add Secrets

on:
  push:
    branches: [ main ]

jobs:
  add-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Add Firebase Key
        env:
          FIREBASE_KEY: $
        run:
          echo FIREBASE_KEY=\"$FIREBASE_KEY\ > ./local.properties